name: eslint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mrdivyansh/eslint-action@v1.0.7
      if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }} 
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
        eslint-rc: .eslintrc.js
        execute-on-files:
          - ./packages
