name: Typescript

on: [push, pull_request]

jobs:
  checkESlint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Checkout 
    uses: actions/checkout@v3
    - name: Eslint check
    uses: krizzu/eslint-check-action@v1.1.0
